/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.cpp                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: rarakoto <rarakoto@student.42antananarivo  +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/01/02 08:48:11 by rarakoto          #+#    #+#             */
/*   Updated: 2025/01/10 09:36:56 by rarakoto         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "FragTrap.hpp"

int main(void)
{
	FragTrap	a("Hasina");

	std::cout << "Hit Points: " << a.getHitPoints() << std::endl;
	std::cout << "Energy Points: " << a.getEnergyPoints() << std::endl;
	std::cout << "Attack Damage: " << a.getAttackDamage() << std::endl;
	a.attack("Harena");
	a.attack("Someone");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Violence");
	a.attack("Another");
	a.takeDamage(10);
	a.highFivesGuys();
	a.takeDamage(100);
	a.highFivesGuys();
	a.highFivesGuys();
	a.attack("Again");
	a.attack("UI");
	a.beRepaired(5);
	std::cout << "Hit Points: " << a.getHitPoints() << std::endl;
	std::cout << "Energy Points: " << a.getEnergyPoints() << std::endl;
	std::cout << "Attack Damage: " << a.getAttackDamage() << std::endl;
	return (0);
}
